


// FIX: Export Language and TranslationKey types to resolve import errors across the application.
// ADDED vi object to translations and used 'as const' for proper type inference.
export const translations = {
  en: {
    // General
    save: "Save",
    delete: "Delete",
    cancel: "Cancel",
    close: "Close",
    edit: "Edit",
    download: "Download",
    view_details: "View Details",
    error_title: "Error!",
    loading_message: "Processing...",
    confirm_delete: "Are you sure you want to delete this? This action cannot be undone.",
    select: "Select",
    transition: "Transition",
    preview: "Preview",
    add: "Add",
    scene: "Scene",
    action: "Action",
    dialogue: "Dialogue",
    no_dialogue: "No dialogue in this scene.",
    image_will_appear_here: "Image will appear here",
    regenerate_image: "Regenerate Image",
    generate_image: "Generate Image",
    type_image: "Image",
    type_images: "Images",
    type_ad: "Ad",
    type_ads: "Ads",
    type_blog: "Blog",
    type_blogs: "Blogs",
    type_storyboard: "Storyboard",
    type_storyboards: "Storyboards",
    type_video: "Video",
    type_videos: "Videos",
    all_content: "All Content",
    zipping: "Zipping...",
    download_selected: "Download Selected",
    items_selected: "{count} items selected",
    
    // Login View
    login_title: "Welcome Back",
    login_subtitle: "Log in to manage your brand assets.",
    register_title: "Create Your Account",
    register_subtitle: "Start your creative journey with us.",
    login_username_label: "Username",
    login_username_placeholder: "e.g., brand_manager",
    login_password_label: "Password",
    login_password_placeholder: "••••••••",
    login_button: "Login",
    register_button: "Register",
    login_error_credentials: "Please enter both username and password.",
    login_toggle_register: "Don't have an account? ",
    login_toggle_login: "Already have an account? ",
    login_note: "Note: Password is for demo purposes only. All data is stored locally in your browser per user account.",
    login_what_is_this: "What is BrandVerse Studio?",
    login_tagline: "Create branded worlds with music, idols, and stories.",
    error_username_not_found: "Username not found. Please check the username or register a new account.",
    error_username_taken: "This username is already taken. Please choose another one.",
    error_editing_not_implemented: "Editing this content type is not yet implemented.",
    error_file_type_not_supported: "File type not supported for analysis. Please use a .txt file.",

    // Info Modal
    info_modal_mission_title: "Our Mission",
    info_modal_mission_text: "Our mission is to empower brands with AI-driven music and storytelling tools, transforming creative concepts into cinematic, resonant experiences. We believe that music is the universal language that turns marketing into culture, building deep connections with audiences worldwide.",
    info_modal_story_title: "Our Story",
    info_modal_story_text: "The journey began with a universal challenge for brands: creating authentic, emotional connections in a noisy world. Traditional advertising often falls flat, but stories and songs resonate deeply. Recognizing this, we built an AI creative studio where brands can bring their narratives to life through music. With just a script, a song, or even a simple idea, BrandVerse Studio generates stunning cinematic storyboards, composes original branded music, and visualizes entire campaigns.\n\nWe call it a 'Studio'—a place where brand stories are composed, orchestrated, and produced.\n\nToday, with our Generative AI platform, we're putting a world-class creative team in your hands. You'll always have fresh, on-brand content that turns your marketing into memorable cultural performances.",
    info_modal_close_button: "Got it!",

    // Header & Bottom Nav
    header_nav_creatives: "Creative Studio",
    header_nav_history: "History",
    header_nav_library: "Library",
    header_nav_assets: "Brand Assets",
    header_welcome: "Welcome,",
    header_logout: "Logout",
    bottom_nav_create: "Create",
    bottom_nav_history: "History",
    bottom_nav_library: "Library",
    bottom_nav_assets: "Assets",

    // BrandCreativesView
    brand: "Brand",
    product: "Product",
    project: "Project",
    no_project_found: "Create a project in Library",
    option_1_title: "Option 1: Use Sample Image (AI learns)",
    option_1_desc: "Upload a single image with person, product, and context. The AI will learn from it and create a higher-quality version.",
    all_in_one_image_label: "All-in-One Sample Image",
    choose_from_library: "Choose from Library",
    option_2_title: "Option 2: Upload Individual Images",
    main_idol_label: "Main Idol",
    supporting_idol_label: "Supporting Idol",
    choose_from_idol_library: "Choose from Idol Library",
    brand_element_label: "Brand Element",
    idol_outfit_label: "Idol Outfit",
    choose_from_outfit_library: "Choose from Outfit Library",
    // FIX: Added missing translation key.
    save_to_outfits_library: "Save to Outfits Library",
    ai_character_analysis_title: "AI Idol Persona",
    analyzing_primary: "Analyzing Primary...",
    gender: "Gender",
    age_range: "Age Range",
    income: "Income",
    location: "Location",
    lifestyle: "Lifestyle",
    analyzing_supporting: "Analyzing Supporting...",
    supporting_character: "Supporting Character",
    suggested_insights: "Suggested Insights (Click to use)",
    regenerate: "Regenerate",
    choose_context_title: "Choose Context",
    ai_suggested_context_title: "AI Suggested Context",
    ai_suggested_context_desc: "Based on the product and character profile, the AI will suggest suitable contexts.",
    analyze_and_suggest: "Analyze & Suggest",
    analyzing: "Analyzing...",
    suggestions: "Suggestions:",
    or_choose_from_library: "Or choose from Context Library",
    custom_context_label: "Enter custom context",
    custom_context_placeholder: "e.g., Product photo on a mossy rock next to a clear stream, with morning sunlight filtering through leaves.",
    camera_shot_title: "Choose Camera Shot",
    image_style_title: "Choose Image Style",
    aspect_ratio_title: "Choose Aspect Ratio & Size",
    review_prompt_label: "Review Generated Prompt",
    generate_scene: "Generate Scene",
    generating: "Generating...",
    creating: "Creating...",
    image_generated: "Image Generated!",
    // FIX: Added 'storyboard' key to support its use in BrandCreativesView.
    storyboard: "Storybeat",
    create_ad: "Create Ad",
    write_blog: "Write Blog",
    create_video: "Create Video",
    save_to_idols: "Save to Idols",
    target_audience: "Target Audience",
    usage_goal_title: "Usage Goal",
    viral_formula_title: "Viral Ad Formula",
    insights_label: "Insight / Pain Point (Optional)",
    insights_placeholder: "e.g., Customers are tired of complex skincare products.",
    video_duration_title: "Choose Video Duration",
    use_storyboard_from_library: "Use Storybeat from Library",
    generate_storyboard: "Generate Storybeat",
    writing_storyboard: "Composing Storybeat...",
    storybeat_from_music_title: "Option 3: Create Storybeat from Music/Script",
    storybeat_from_music_desc: "Upload a song (MP3) or script (TXT, PDF) and the AI will automatically generate a storybeat based on the content and mood.",
    song_or_script_file_label: "Song or Script File",
    image_gen: "Quick Visuals",
    content_creation: "Text Content",
    content_strategy: "Content Strategy",
    paid_ad: "Paid Ad",
    seo_blog: "SEO / Blog",
    base_image_title: "1. Base Image",
    upload_select_base_image: "Upload or Select Base Image",
    ad_specifics_title: "2. Ad Specifics",
    ad_goal_title: "Ad Goal",
    generate_ad_copy: "Generate Ad Copy with AI",
    generating_copy: "Generating...",
    choose_ad_copy_title: "3. Choose Ad Copy Idea",
    edit_refine_title: "4. Edit & Refine",
    headline_label: "Headline",
    headline_placeholder: "e.g., Summer Sale is ON!",
    body_label: "Body",
    body_placeholder: "Briefly describe the offer...",
    cta_label: "Call to Action",
    cta_placeholder: "e.g., Shop Now!",
    text_style_title: "5. Text Style",
    ad_font_title: "Ad Font",
    save_ad_to_library: "Save Ad to Library",
    saving: "Saving...",
    featured_image_title: "1. Featured Image",
    upload_select_featured_image: "Upload or Select Featured Image",
    blog_details_title: "2. Blog Details",
    blog_length_title: "Blog Length",
    blog_goal_title: "Blog Goal",
    main_topic_label: "Main Topic",
    main_topic_placeholder: "e.g., 5 steps for a men's morning skincare routine",
    keywords_label: "Main Keywords (comma-separated)",
    keywords_placeholder: "e.g., men's skincare, face wash",
    generate_blog_ideas: "Generate Blog Ideas",
    choose_blog_idea: "Choose a Blog Idea",
    generate_blog: "Generate Blog Post",
    writing_blog: "Writing blog...",
    platform_previews: "Platform Previews",
    reload_preview: "Reload Preview",
    blog_preview_here: "Blog preview will appear here",
    blog_preview_prompt: "Enter a topic and keywords to start.",
    generate_all_illustrations: "Generate All Illustrations",
    generating_image_progress: "Generating image {current}/{total}...",
    done: "Done!",
    refine_content_title: "Refine & Humanize Content",
    ai_detection_title: "AI Analysis",
    ai_detection_desc: "Let the AI evaluate if the text sounds machine-written. The higher the score, the more it needs to be 'humanized'.",
    check_ai_score: "Check AI Score",
    analyzing_text: "Analyzing...",
    reason: "Reason:",
    humanize_title: "Rewrite to be more 'Human'",
    humanize_desc: "Choose a writing style for the AI to emulate and create a more natural, charismatic version of the content.",
    advanced_options: "Advanced Options",
    pov_label: "Point of View",
    custom_persona_label: "Custom Persona (Optional)",
    custom_persona_placeholder: "e.g., A tech expert in his 40s, skeptical but fair, loves technical details.",
    humanize_button: "Humanize",
    rewriting: "Rewriting...",
    compare_versions: "Compare Versions",
    original_ai: "Original AI",
    humanized: "Humanized",
    use_this_version: "Use This Version",
    storyboard_results_title: "Storybeat Preview",
    generate_all_images: "Generate All Images",
    generate_full_video: "Generate Full Video",
    no_active_brand: "Welcome to Creative Studio",
    no_active_brand_prompt: "Please create or select a brand in the",
    brand_assets_link: "Brand Assets",
    no_active_brand_prompt_2: "tab to begin.",
    results_here: "Results will appear here",
    fill_info_prompt: "Fill in the information and start creating!",
    select_product_prompt: "Please select a product to begin.",
    sync_with_song_title: "🎵 Sync with Song",
    sync_with_song_desc: "Upload a song to sync lyrics and timing with your generated scene.",
    sync_with_song_desc_manual: "Upload a song to automatically detect duration, or enter lyrics manually to guide the AI scriptwriter.",
    upload_song_label: "Upload Song (MP3/WAV)",
    enter_lyrics_label: "Enter Lyrics (Optional)",
    enter_lyrics_placeholder: "Enter or paste song lyrics here to guide the storyboard generation...",
    style_of_music_label: "Style of Music",
    lyrics_and_timing_title: "Lyrics & Timing",
    sync_lyric_button: "Sync Lyric",
    voice_type: "Voice Type",
    music_vibe: "Music Vibe",
    role: "Role",
    music_vibe_romantic: "Romantic",
    music_vibe_powerful: "Powerful",
    music_vibe_fun: "Fun",
    music_vibe_cinematic: "Cinematic",
    clone_from_source_title: "🌟 Option 3: Create from Inspiration (Advanced)",
    clone_from_source_desc: "Provide a YouTube link or a script file. The AI will analyze its structure, pacing, and visual style to create a new, original storyboard for your product.",
    youtube_link_label: "YouTube URL",
    youtube_link_placeholder: "e.g., https://www.youtube.com/watch?v=...",
    or_upload_file: "OR",
    inspiration_file_label: "Upload Script or Reference File",
    analyzing_inspiration: "Analyzing Inspiration...",
    analyze_and_generate_storybeat: "Analyze & Generate Storybeat",

    // History & Library View
    history_title: "Creative History",
    history_subtitle: "Review and manage all your generated content ({count} items).",
    select_items: "Select Items",
    cancel_selection: "Cancel Selection",
    select_all: "Select All ({count})",
    deselect_all: "Deselect All",
    confirm_delete_image: "Are you sure you want to delete this image?",
    confirm_delete_ad: "Are you sure you want to delete this ad creative?",
    confirm_delete_blog: "Are you sure you want to delete this blog post?",
    confirm_delete_storyboard: "Are you sure you want to delete this storyboard?",
    confirm_delete_video: "Are you sure you want to delete this video?",
    download_script: "Download Script",
    view_storyboard: "View Storyboard",
    view_video: "View Video",
    storyboard_details_title: "Storyboard Details",
    full_script: "Full Script",
    frames: "Frames",
    ad_creative_title: "Ad Creative",
    preview_not_available: "Preview not available for this placement.",
    blog_post_title: "Blog Post",
    view_post: "View Post",
    no_history_title: "No History Yet",
    no_history_prompt: "Start creating in the Creative Studio and your work will appear here.",
    no_type_title: "No {type} Found",
    no_type_prompt: "There are no {type} items in your history. Try creating some!",
    projects: "Projects",
    new_project: "New Project",
    all_content_in_project: "All content in this project",
    item_count: "{count} items",
    create_project_title: "Create New Project",
    project_name_label: "Project Name",
    project_name_placeholder: "e.g., Q4 Campaign Launch",
    save_project: "Save Project",
    no_content_title: "This space is ready for your ideas!",
    no_content_prompt: "You haven't created any content yet. Go to the Creative Studio to get started.",
    no_content_in_project_prompt: "This project is empty. Start creating content to add it here.",
    select_a_project: "Select a Project",
    confirm_delete_project: "Are you sure you want to delete this project? All content inside will also be deleted.",
    
    // AssetsView
    assets_title: "Brand Assets",
    assets_subtitle: "Manage your brand profiles, products, and visual assets.",
    your_brands: "Your Brands",
    create_new_brand: "Create New Brand",
    edit_brand_title: "Editing Brand:",
    currently_active: "Currently Active",
    set_active_and_create: "Set Active & Create",
    no_brand_selected_title: "No Brand Selected",
    no_brand_selected_prompt: "Select a brand from the left panel to edit its assets, or create a new one.",
    new_brand_placeholder: "New Brand",
    active_status: "ACTIVE",
    idols_title: "Idol Library",
    outfits_title: "Outfit Library",
    idol_label: "Idol",
    outfit_label: "Outfit",
    add_new_idol_label: "Upload New Idol",
    add_new_outfit_label: "Upload New Outfit",
    // FIX: Added missing translation keys for AssetPickerModal
    add_new_main_idol: "Upload new Main Idol",
    add_new_supporting_idol: "Upload new Supporting Idol",
    add_new_outfit: "Upload new Outfit",
    no_assets_of_type_prompt: "No {type} yet. Upload one to get started.",
    new_product_placeholder: "New Product",
    product_full_name_label: "Product Full Name",
    product_short_name_label: "Product Short Name (for AI)",
    product_sku_label: "SKU / ID",
    product_image_label: "Product Image (Packshot)",
    product_info_file_label: "Product Info File (Optional)",
    brand_tone_notes_label: "Brand Tone & Notes for AI",
    brand_name_label: "Brand Name",
    brand_colors_label: "Brand Colors",
    brand_logo_label: "Brand Logo",
    brand_guideline_label: "Brand Guideline (Optional)",
    product_details_title: "Product Details",
    add_product: "Add Product",
    no_products_prompt: "This brand has no products yet. Add one to get started.",

    // Checklist Modal
    checklist_title: "Pre-Flight Quality Checklist",

    // File Upload
    file_upload_converting: "Converting...",
    file_upload_ai_analyzing: "AI Analyzing...",
    file_upload_action: "Upload a file",
    file_upload_drag_drop: "or drag and drop",
    file_upload_types: "PNG, JPG, GIF, HEIC up to 10MB",

    // Asset Picker Modal
    choose_asset_title: "Choose an Asset",
    no_assets_in_library: "You have no assets of this type in your library.",

    // Brand Styles
    style_neon_stage: "Neon Stage",
    style_urban_night_drive: "Urban Night Drive",
    style_rooftop_sunset: "Rooftop Sunset",
    style_enchanted_forest: "Enchanted Forest",
    style_industrial_dance: "Industrial Dance",
    style_art_gallery_after_hours: "Art Gallery After Hours",
    style_cloud_dreamscape: "Cloud Dreamscape",
    style_vibrant_street_style: "Vibrant Street Style",
    style_high_fashion_runway: "High Fashion Runway",
    style_retro_futurism: "Retro-Futurism",
    style_luxury_penthouse: "Luxury Penthouse",
    style_traditional_garden: "Traditional Garden",
    style_pool_party: "Pool Party",
    style_bar_pub: "Bar/Pub",
    style_bathroom_modern: "Modern Bathroom",
    style_gym_locker: "Gym Locker Room",
    style_café_window: "Café Window",
    style_urban_rooftop: "Urban Rooftop",
    style_living_sofa: "Living Room Sofa",
    style_desk_minimal: "Minimalist Desk",
    style_outdoor_park: "Outdoor Park",
    style_shower_tile: "Shower Tiles",
    style_street_neon: "Neon Street",
    style_tet_holiday: "Tết Holiday",
    style_beach_sunset: "Beach Sunset",
    style_sidewalk_eatery: "Sidewalk Eatery",
    style_yoga_retreat: "Yoga Retreat",
    style_cocktail_bar: "Cocktail Bar",
    style_airport_terminal: "Airport Terminal",
    style_classic_library: "Classic Library",
    style_mountain_camping: "Mountain Camping",
    style_art_gallery: "Art Gallery",
    style_golf_course: "Golf Course",
    style_tet_flower_market: "Tết Flower Market",
    style_review: "Review Style",
    style_custom_prompt: "Custom Prompt",

    // Camera Shots
    shot_auto: "Auto",
    shot_els: "Extreme Long Shot (ELS)",
    shot_ls: "Long Shot (LS)",
    shot_mls: "Medium Long Shot (MLS)",
    shot_ms: "Medium Shot (MS)",
    shot_mcu: "Medium Close-Up (MCU)",
    shot_ecu: "Extreme Close-Up (ECU)",

    // Aspect Ratios
    aspect_ratio_16_9: "16:9 (Landscape)",
    aspect_ratio_9_16: "9:16 (Portrait/Story)",
    aspect_ratio_1_1: "1:1 (Square)",

    // Genders
    gender_male: "Male",
    gender_female: "Female",
    gender_any: "Any",

    // Viral Ad Formulas
    viral_formula_idol_centric_name: "Idol-Centric Story",
    viral_formula_idol_centric_desc: "Focuses on a day in the life or a specific story arc of the idol, with the product integrated naturally.",
    viral_formula_lyrical_narrative_name: "Lyrical Narrative",
    viral_formula_lyrical_narrative_desc: "The story is driven by the song's lyrics, creating a music video feel where the product is a key element.",
    viral_formula_vibe_montage_name: "Vibe Montage",
    viral_formula_vibe_montage_desc: "A series of aesthetically pleasing, quick-cut shots that establish a mood or lifestyle associated with the product.",
    viral_formula_emotional_journey_name: "Emotional Journey",
    viral_formula_emotional_journey_desc: "Tells a story with a clear emotional arc (e.g., struggle to triumph) where the product plays a resolving role.",
     // Brand Film
    viral_formula_brand_origin_story_name: "Brand Origin Story",
    viral_formula_brand_origin_story_desc: "Tell the story of why the brand was created, its mission, and its values.",
    viral_formula_customer_testimonial_name: "Customer Testimonial",
    viral_formula_customer_testimonial_desc: "Feature a real customer's journey and how the product positively impacted them.",
    viral_formula_behind_the_scenes_name: "Behind the Scenes",
    viral_formula_behind_the_scenes_desc: "Show the craftsmanship, people, or process behind the product to build authenticity.",
    viral_formula_product_philosophy_name: "Product Philosophy",
    viral_formula_product_philosophy_desc: "Explain the 'why' behind the product's design, ingredients, or features, connecting to a bigger idea.",
    // Social Media Story
    viral_formula_ugc_challenge_name: "UGC Challenge",
    viral_formula_ugc_challenge_desc: "Create a simple, repeatable trend or challenge that encourages user-generated content.",
    viral_formula_quick_tip_tutorial_name: "Quick Tip / Tutorial",
    viral_formula_quick_tip_tutorial_desc: "Provide value by teaching the audience something useful related to the product in a fast-paced format.",
    viral_formula_trending_sound_meme_name: "Trending Sound / Meme",
    viral_formula_trending_sound_meme_desc: "Adapt a popular audio or meme format to the brand's niche in a creative way.",
    viral_formula_day_in_the_life_takeover_name: "A Day in the Life / Takeover",
    viral_formula_day_in_the_life_takeover_desc: "Show a relatable 'day in the life' from the perspective of an idol or customer using the product.",
    // Sales Video
    viral_formula_problem_agitate_solve_name: "Problem-Agitate-Solve",
    viral_formula_problem_agitate_solve_desc: "Identify a customer pain point, emphasize the problem, and present the product as the perfect solution.",
    viral_formula_unboxing_first_impression_name: "Unboxing / First Impression",
    viral_formula_unboxing_first_impression_desc: "Capture the excitement of unboxing and using the product for the first time.",
    viral_formula_before_after_transformation_name: "Before & After Transformation",
    viral_formula_before_after_transformation_desc: "Visually demonstrate the clear, tangible results of using the product.",
    viral_formula_feature_benefit_demo_name: "Feature-Benefit Demo",
    viral_formula_feature_benefit_demo_desc: "Clearly demonstrate a key feature and explain its direct benefit to the customer.",

    // Ad Goals
    ad_goal_conversion_name: "Conversion",
    ad_goal_conversion_desc: "Focus on driving immediate sales with clear calls-to-action and benefit-driven copy.",
    ad_goal_engagement_name: "Engagement",
    ad_goal_engagement_desc: "Aim to get likes, comments, and shares by being entertaining, asking questions, or being relatable.",
    ad_goal_awareness_name: "Awareness",
    ad_goal_awareness_desc: "Introduce the brand or product to a new audience, focusing on brand story and unique selling points.",

    // Blog Lengths
    blog_length_short: "Short (~300 words)",
    blog_length_medium: "Medium (~800 words)",
    blog_length_long: "Long (1500+ words)",

    // Blog Goals
    blog_goal_seo: "SEO Ranking",
    blog_goal_engagement: "Community Engagement",
    blog_goal_leadgen: "Lead Generation",
    blog_goal_product: "Product Promotion",
    
    // Humanize Tones
    humanize_everyday_user: "Everyday User",
    humanize_teacher: "Helpful Teacher",
    humanize_online_reviewer: "Online Reviewer",
    humanize_blog_commenter: "Blog Commenter",
    
    // Video Usage Goals
    video_goal_mv_name: "Music Video (MV)",
    video_goal_mv_desc: "A full-fledged music video to promote a song, featuring the idol and product.",
    video_goal_brand_film_name: "Brand Film",
    video_goal_brand_film_desc: "A short, cinematic film that tells a story about the brand's values, with the product playing a role.",
    video_goal_social_story_name: "Social Media Story",
    video_goal_social_story_desc: "A short, vertical-format video designed for platforms like Instagram Stories or TikTok.",
    video_goal_sales_video_name: "Sales Video",
    video_goal_sales_video_desc: "A direct-response video focused on demonstrating the product and driving conversions.",
  },
  vi: {
    // General
    save: "Lưu",
    delete: "Xóa",
    cancel: "Hủy",
    close: "Đóng",
    edit: "Chỉnh sửa",
    download: "Tải xuống",
    view_details: "Xem chi tiết",
    error_title: "Lỗi!",
    loading_message: "Đang xử lý...",
    confirm_delete: "Bạn có chắc chắn muốn xóa mục này? Hành động này không thể hoàn tác.",
    select: "Chọn",
    transition: "Chuyển cảnh",
    preview: "Xem trước",
    add: "Thêm",
    scene: "Bối cảnh",
    action: "Hành động",
    dialogue: "Lời thoại",
    no_dialogue: "Không có lời thoại trong cảnh này.",
    image_will_appear_here: "Ảnh sẽ hiện ở đây",
    regenerate_image: "Tạo lại ảnh",
    generate_image: "Tạo ảnh",
    type_image: "Ảnh",
    type_images: "Ảnh",
    type_ad: "Quảng cáo",
    type_ads: "Quảng cáo",
    type_blog: "Blog",
    type_blogs: "Blog",
    type_storyboard: "Kịch bản",
    type_storyboards: "Kịch bản",
    type_video: "Video",
    type_videos: "Video",
    all_content: "Tất cả nội dung",
    zipping: "Đang nén...",
    download_selected: "Tải mục đã chọn",
    items_selected: "{count} mục đã được chọn",

    // Login View
    login_title: "Chào mừng trở lại",
    login_subtitle: "Đăng nhập để quản lý tài sản thương hiệu của bạn.",
    register_title: "Tạo tài khoản",
    register_subtitle: "Bắt đầu hành trình sáng tạo của bạn.",
    login_username_label: "Tên người dùng",
    login_username_placeholder: "ví dụ: brand_manager",
    login_password_label: "Mật khẩu",
    login_password_placeholder: "••••••••",
    login_button: "Đăng nhập",
    register_button: "Đăng ký",
    login_error_credentials: "Vui lòng nhập tên người dùng và mật khẩu.",
    login_toggle_register: "Chưa có tài khoản? ",
    login_toggle_login: "Đã có tài khoản? ",
    login_note: "Lưu ý: Mật khẩu chỉ dùng cho mục đích demo. Tất cả dữ liệu được lưu trữ cục bộ trong trình duyệt của bạn theo từng tài khoản.",
    login_what_is_this: "BrandVerse Studio là gì?",
    login_tagline: "Tạo ra thế giới thương hiệu với âm nhạc, thần tượng và câu chuyện.",
    error_username_not_found: "Tên người dùng không tồn tại. Vui lòng kiểm tra lại hoặc đăng ký tài khoản mới.",
    error_username_taken: "Tên người dùng này đã có người sử dụng. Vui lòng chọn tên khác.",
    error_editing_not_implemented: "Chỉnh sửa loại nội dung này chưa được hỗ trợ.",
    error_file_type_not_supported: "Loại tệp không được hỗ trợ để phân tích. Vui lòng sử dụng tệp .txt.",

    // Info Modal
    info_modal_mission_title: "Sứ mệnh",
    info_modal_mission_text: "Sứ mệnh của chúng tôi là trao quyền cho các thương hiệu bằng các công cụ kể chuyện và âm nhạc do AI điều khiển, biến các ý tưởng sáng tạo thành trải nghiệm điện ảnh, có sức ảnh hưởng. Chúng tôi tin rằng âm nhạc là ngôn ngữ toàn cầu biến marketing thành văn hóa, xây dựng kết nối sâu sắc với khán giả trên toàn thế giới.",
    info_modal_story_title: "Câu chuyện",
    info_modal_story_text: "Hành trình bắt đầu với một thách thức chung của các thương hiệu: tạo ra kết nối cảm xúc, chân thực trong một thế giới ồn ào. Quảng cáo truyền thống thường không hiệu quả, nhưng những câu chuyện và bài hát lại có sức ảnh hưởng sâu sắc. Nhận thấy điều này, chúng tôi đã xây dựng một studio sáng tạo AI nơi các thương hiệu có thể đưa câu chuyện của mình vào cuộc sống thông qua âm nhạc. Chỉ với một kịch bản, một bài hát, hoặc thậm chí một ý tưởng đơn giản, BrandVerse Studio tạo ra những kịch bản phân cảnh điện ảnh tuyệt đẹp, sáng tác nhạc hiệu độc quyền và hình dung toàn bộ chiến dịch.\n\nChúng tôi gọi đó là 'Studio'—một nơi mà các câu chuyện thương hiệu được sáng tác, dàn dựng và sản xuất.\n\nHôm nay, với nền tảng Generative AI của chúng tôi, chúng tôi đang đặt một đội ngũ sáng tạo đẳng cấp thế giới vào tay bạn. Bạn sẽ luôn có nội dung mới mẻ, đúng với thương hiệu, biến hoạt động marketing của bạn thành những màn trình diễn văn hóa đáng nhớ.",
    info_modal_close_button: "Đã hiểu!",

    // Header & Bottom Nav
    header_nav_creatives: "Studio Sáng tạo",
    header_nav_history: "Lịch sử",
    header_nav_library: "Thư viện",
    header_nav_assets: "Tài sản Thương hiệu",
    header_welcome: "Chào,",
    header_logout: "Đăng xuất",
    bottom_nav_create: "Sáng tạo",
    bottom_nav_history: "Lịch sử",
    bottom_nav_library: "Thư viện",
    bottom_nav_assets: "Tài sản",

    // BrandCreativesView
    brand: "Thương hiệu",
    product: "Sản phẩm",
    project: "Dự án",
    no_project_found: "Tạo dự án trong Thư viện",
    option_1_title: "Lựa chọn 1: Dùng ảnh mẫu (AI tự học)",
    option_1_desc: "Tải lên một ảnh duy nhất có người, sản phẩm và bối cảnh. AI sẽ học từ đó và tạo ra phiên bản chất lượng cao hơn.",
    all_in_one_image_label: "Ảnh mẫu All-in-One",
    choose_from_library: "Chọn từ Thư viện",
    option_2_title: "Lựa chọn 2: Tải lên các ảnh riêng lẻ",
    main_idol_label: "Idol chính",
    supporting_idol_label: "Idol phụ",
    choose_from_idol_library: "Chọn từ Thư viện Idol",
    brand_element_label: "Yếu tố Thương hiệu",
    idol_outfit_label: "Trang phục Idol",
    choose_from_outfit_library: "Chọn từ Thư viện Trang phục",
    // FIX: Added missing translation key.
    save_to_outfits_library: "Lưu vào Thư viện Trang phục",
    ai_character_analysis_title: "AI Phân tích Chân dung Idol",
    analyzing_primary: "Đang phân tích Idol chính...",
    gender: "Giới tính",
    age_range: "Độ tuổi",
    income: "Thu nhập",
    location: "Địa điểm",
    lifestyle: "Phong cách sống",
    analyzing_supporting: "Đang phân tích Idol phụ...",
    supporting_character: "Nhân vật phụ",
    suggested_insights: "Insight đề xuất (Nhấn để dùng)",
    regenerate: "Tạo lại",
    choose_context_title: "Chọn bối cảnh",
    ai_suggested_context_title: "Bối cảnh do AI đề xuất",
    ai_suggested_context_desc: "Dựa trên sản phẩm và chân dung nhân vật, AI sẽ đề xuất các bối cảnh phù hợp.",
    analyze_and_suggest: "Phân tích & Đề xuất",
    analyzing: "Đang phân tích...",
    suggestions: "Đề xuất:",
    or_upload_file: "HOẶC",
    custom_context_label: "Nhập bối cảnh tùy chỉnh",
    custom_context_placeholder: "VD: Ảnh sản phẩm trên một tảng đá rêu phong cạnh dòng suối trong, ánh nắng ban mai xuyên qua kẽ lá.",
    camera_shot_title: "Chọn góc máy",
    image_style_title: "Chọn phong cách ảnh",
    aspect_ratio_title: "Chọn tỉ lệ & kích thước",
    review_prompt_label: "Xem lại Prompt đã tạo",
    generate_scene: "Tạo cảnh",
    generating: "Đang tạo...",
    creating: "Đang tạo...",
    image_generated: "Đã tạo ảnh!",
    // FIX: Added 'storyboard' key to support its use in BrandCreativesView.
    storyboard: "Storybeat",
    create_ad: "Tạo quảng cáo",
    write_blog: "Viết Blog",
    create_video: "Tạo Video",
    save_to_idols: "Lưu vào Thư viện Idol",
    target_audience: "Đối tượng mục tiêu",
    usage_goal_title: "Mục đích sử dụng",
    viral_formula_title: "Công thức Viral",
    insights_label: "Insight / Nỗi đau (Tùy chọn)",
    insights_placeholder: "VD: Khách hàng mệt mỏi với các sản phẩm chăm sóc da phức tạp.",
    video_duration_title: "Chọn thời lượng video",
    use_storyboard_from_library: "Dùng Storybeat từ Thư viện",
    generate_storyboard: "Tạo Storybeat",
    writing_storyboard: "Đang sáng tác Storybeat...",
    storybeat_from_music_title: "Lựa chọn 3: Tạo Storybeat từ Nhạc/Kịch bản",
    storybeat_from_music_desc: "Tải lên một bài hát (MP3) hoặc kịch bản (TXT, PDF) và AI sẽ tự động tạo một storybeat dựa trên nội dung và tâm trạng.",
    song_or_script_file_label: "Tệp bài hát hoặc kịch bản",
    image_gen: "Ảnh nhanh",
    content_creation: "Nội dung chữ",
    content_strategy: "Chiến lược Nội dung",
    paid_ad: "Quảng cáo trả phí",
    seo_blog: "SEO / Blog",
    base_image_title: "1. Ảnh nền",
    upload_select_base_image: "Tải lên hoặc chọn ảnh nền",
    ad_specifics_title: "2. Chi tiết quảng cáo",
    ad_goal_title: "Mục tiêu quảng cáo",
    generate_ad_copy: "Tạo nội dung quảng cáo với AI",
    generating_copy: "Đang viết...",
    choose_ad_copy_title: "3. Chọn ý tưởng nội dung",
    edit_refine_title: "4. Chỉnh sửa & Tinh chỉnh",
    headline_label: "Tiêu đề",
    headline_placeholder: "VD: Siêu sale mùa hè!",
    body_label: "Nội dung",
    body_placeholder: "Mô tả ngắn gọn về ưu đãi...",
    cta_label: "Kêu gọi hành động",
    cta_placeholder: "VD: Mua ngay!",
    text_style_title: "5. Phong cách chữ",
    ad_font_title: "Font chữ quảng cáo",
    save_ad_to_library: "Lưu quảng cáo vào Thư viện",
    saving: "Đang lưu...",
    featured_image_title: "1. Ảnh đại diện",
    upload_select_featured_image: "Tải lên hoặc chọn ảnh đại diện",
    blog_details_title: "2. Chi tiết Blog",
    blog_length_title: "Độ dài Blog",
    blog_goal_title: "Mục tiêu Blog",
    main_topic_label: "Chủ đề chính",
    main_topic_placeholder: "VD: 5 bước chăm sóc da buổi sáng cho nam giới",
    keywords_label: "Từ khóa chính (cách nhau bằng dấu phẩy)",
    keywords_placeholder: "VD: chăm sóc da nam, sữa rửa mặt",
    generate_blog_ideas: "Tạo ý tưởng Blog",
    choose_blog_idea: "Chọn một ý tưởng Blog",
    generate_blog: "Tạo bài Blog",
    writing_blog: "Đang viết blog...",
    platform_previews: "Xem trước trên các nền tảng",
    reload_preview: "Tải lại xem trước",
    blog_preview_here: "Bản xem trước blog sẽ hiện ở đây",
    blog_preview_prompt: "Nhập chủ đề và từ khóa để bắt đầu.",
    generate_all_illustrations: "Tạo tất cả ảnh minh họa",
    generating_image_progress: "Đang tạo ảnh {current}/{total}...",
    done: "Hoàn tất!",
    refine_content_title: "Tinh chỉnh & Nhân hóa Nội dung",
    ai_detection_title: "Phân tích mức độ AI",
    ai_detection_desc: "Để AI tự đánh giá xem văn bản có giống máy viết không. Điểm càng cao, văn bản càng cần được 'nhân hóa'.",
    check_ai_score: "Chấm điểm AI",
    analyzing_text: "Đang phân tích...",
    reason: "Lý do:",
    humanize_title: "Viết lại cho 'Người' hơn",
    humanize_desc: "Chọn một phong cách viết để AI học theo và tạo ra phiên bản nội dung tự nhiên, có cá tính hơn.",
    advanced_options: "Tùy chọn nâng cao",
    pov_label: "Ngôi xưng",
    custom_persona_label: "Chân dung tùy chỉnh (Tùy chọn)",
    custom_persona_placeholder: "VD: Một chuyên gia công nghệ U40, hoài nghi nhưng công bằng, thích các chi tiết kỹ thuật.",
    humanize_button: "Nhân hóa",
    rewriting: "Đang viết lại...",
    compare_versions: "So sánh phiên bản",
    original_ai: "AI Gốc",
    humanized: "Đã nhân hóa",
    use_this_version: "Sử dụng phiên bản này",
    storyboard_results_title: "Xem trước Storybeat",
    generate_all_images: "Tạo tất cả ảnh",
    generate_full_video: "Tạo video hoàn chỉnh",
    no_active_brand: "Chào mừng đến với Studio Sáng tạo",
    no_active_brand_prompt: "Vui lòng tạo hoặc chọn một thương hiệu trong tab",
    brand_assets_link: "Tài sản Thương hiệu",
    no_active_brand_prompt_2: "để bắt đầu.",
    results_here: "Kết quả sẽ xuất hiện ở đây",
    fill_info_prompt: "Điền thông tin và bắt đầu sáng tạo!",
    select_product_prompt: "Vui lòng chọn một sản phẩm để bắt đầu.",
    sync_with_song_title: "🎵 Đồng bộ với bài hát",
    sync_with_song_desc: "Tải lên một bài hát để đồng bộ lời và thời gian với cảnh được tạo.",
    sync_with_song_desc_manual: "Tải lên bài hát để tự động nhận diện thời lượng, hoặc nhập lời bài hát thủ công để hướng dẫn AI viết kịch bản.",
    upload_song_label: "Tải bài hát (MP3/WAV)",
    enter_lyrics_label: "Nhập lời bài hát (Tùy chọn)",
    enter_lyrics_placeholder: "Nhập hoặc dán lời bài hát vào đây để định hướng việc tạo kịch bản...",
    style_of_music_label: "Phong cách âm nhạc",
    lyrics_and_timing_title: "Lời & Thời gian",
    sync_lyric_button: "Đồng bộ lời",
    voice_type: "Loại giọng",
    music_vibe: "Cảm xúc âm nhạc",
    role: "Vai trò",
    music_vibe_romantic: "Lãng mạn",
    music_vibe_powerful: "Mạnh mẽ",
    music_vibe_fun: "Vui vẻ",
    music_vibe_cinematic: "Điện ảnh",
    clone_from_source_title: "🌟 Lựa chọn 3: Tạo từ nguồn cảm hứng (Nâng cao)",
    clone_from_source_desc: "Cung cấp một liên kết YouTube hoặc một tệp kịch bản. AI sẽ phân tích cấu trúc, nhịp độ và phong cách hình ảnh để tạo ra một kịch bản mới, độc đáo cho sản phẩm của bạn.",
    youtube_link_label: "URL YouTube",
    youtube_link_placeholder: "VD: https://www.youtube.com/watch?v=...",
    inspiration_file_label: "Tải lên Kịch bản hoặc Tệp tham khảo",
    analyzing_inspiration: "Đang phân tích nguồn cảm hứng...",
    analyze_and_generate_storybeat: "Phân tích & Tạo Storybeat",

    // History & Library View
    history_title: "Lịch sử Sáng tạo",
    history_subtitle: "Xem lại và quản lý tất cả nội dung đã tạo của bạn ({count} mục).",
    select_items: "Chọn mục",
    cancel_selection: "Hủy chọn",
    select_all: "Chọn tất cả ({count})",
    deselect_all: "Bỏ chọn tất cả",
    confirm_delete_image: "Bạn có chắc muốn xóa ảnh này?",
    confirm_delete_ad: "Bạn có chắc muốn xóa quảng cáo này?",
    confirm_delete_blog: "Bạn có chắc muốn xóa bài blog này?",
    confirm_delete_storyboard: "Bạn có chắc muốn xóa kịch bản này?",
    confirm_delete_video: "Bạn có chắc muốn xóa video này?",
    download_script: "Tải kịch bản",
    view_storyboard: "Xem kịch bản",
    view_video: "Xem video",
    storyboard_details_title: "Chi tiết kịch bản",
    full_script: "Kịch bản đầy đủ",
    frames: "Phân cảnh",
    ad_creative_title: "Sáng tạo Quảng cáo",
    preview_not_available: "Không có bản xem trước cho vị trí này.",
    blog_post_title: "Bài Blog",
    view_post: "Xem bài viết",
    no_history_title: "Chưa có lịch sử",
    no_history_prompt: "Bắt đầu sáng tạo trong Studio và tác phẩm của bạn sẽ xuất hiện ở đây.",
    no_type_title: "Không tìm thấy {type}",
    no_type_prompt: "Không có mục {type} nào trong lịch sử của bạn. Hãy thử tạo một vài cái!",
    projects: "Dự án",
    new_project: "Dự án mới",
    all_content_in_project: "Tất cả nội dung trong dự án này",
    item_count: "{count} mục",
    create_project_title: "Tạo dự án mới",
    project_name_label: "Tên dự án",
    project_name_placeholder: "VD: Chiến dịch ra mắt Q4",
    save_project: "Lưu dự án",
    no_content_title: "Không gian này sẵn sàng cho ý tưởng của bạn!",
    no_content_prompt: "Bạn chưa tạo nội dung nào. Hãy đến Studio Sáng tạo để bắt đầu.",
    no_content_in_project_prompt: "Dự án này trống. Bắt đầu tạo nội dung để thêm vào đây.",
    select_a_project: "Chọn một dự án",
    confirm_delete_project: "Bạn có chắc chắn muốn xóa dự án này? Tất cả nội dung bên trong cũng sẽ bị xóa.",

    // AssetsView
    assets_title: "Tài sản Thương hiệu",
    assets_subtitle: "Quản lý hồ sơ thương hiệu, sản phẩm và tài sản hình ảnh của bạn.",
    your_brands: "Thương hiệu của bạn",
    create_new_brand: "Tạo thương hiệu mới",
    edit_brand_title: "Chỉnh sửa thương hiệu:",
    currently_active: "Đang hoạt động",
    set_active_and_create: "Kích hoạt & Sáng tạo",
    no_brand_selected_title: "Chưa chọn thương hiệu",
    no_brand_selected_prompt: "Chọn một thương hiệu từ bảng điều khiển bên trái để chỉnh sửa tài sản, hoặc tạo một thương hiệu mới.",
    new_brand_placeholder: "Thương hiệu mới",
    active_status: "ĐANG HOẠT ĐỘNG",
    idols_title: "Thư viện Idol",
    outfits_title: "Thư viện Trang phục",
    idol_label: "Idol",
    outfit_label: "Trang phục",
    add_new_idol_label: "Tải lên Idol mới",
    add_new_outfit_label: "Tải lên Trang phục mới",
    // FIX: Added missing translation keys for AssetPickerModal
    add_new_main_idol: "Tải lên Idol chính mới",
    add_new_supporting_idol: "Tải lên Idol phụ mới",
    add_new_outfit: "Tải lên Trang phục mới",
    no_assets_of_type_prompt: "Chưa có {type}. Tải lên một cái để bắt đầu.",
    new_product_placeholder: "Sản phẩm mới",
    product_full_name_label: "Tên sản phẩm đầy đủ",
    product_short_name_label: "Tên sản phẩm ngắn (cho AI)",
    product_sku_label: "SKU / ID",
    product_image_label: "Ảnh sản phẩm (Packshot)",
    product_info_file_label: "Tệp thông tin sản phẩm (Tùy chọn)",
    brand_tone_notes_label: "Tông giọng & Ghi chú cho AI",
    brand_name_label: "Tên thương hiệu",
    brand_colors_label: "Màu sắc thương hiệu",
    brand_logo_label: "Logo thương hiệu",
    brand_guideline_label: "Brand Guideline (Tùy chọn)",
    product_details_title: "Chi tiết sản phẩm",
    add_product: "Thêm sản phẩm",
    no_products_prompt: "Thương hiệu này chưa có sản phẩm nào. Thêm một sản phẩm để bắt đầu.",

    // Checklist Modal
    checklist_title: "Danh sách kiểm tra chất lượng",

    // File Upload
    file_upload_converting: "Đang chuyển đổi...",
    file_upload_ai_analyzing: "AI đang phân tích...",
    file_upload_action: "Tải tệp lên",
    file_upload_drag_drop: "hoặc kéo và thả",
    file_upload_types: "PNG, JPG, GIF, HEIC tối đa 10MB",

    // Asset Picker Modal
    choose_asset_title: "Chọn một tài sản",
    no_assets_in_library: "Bạn không có tài sản loại này trong thư viện.",

    // Brand Styles
    style_neon_stage: "Sân khấu Neon",
    style_urban_night_drive: "Lái xe đêm trong thành phố",
    style_rooftop_sunset: "Hoàng hôn trên sân thượng",
    style_enchanted_forest: "Khu rừng mê hoặc",
    style_industrial_dance: "Vũ đạo trong nhà kho",
    style_art_gallery_after_hours: "Triển lãm nghệ thuật đêm",
    style_cloud_dreamscape: "Cõi mộng trên mây",
    style_vibrant_street_style: "Phong cách đường phố sôi động",
    style_high_fashion_runway: "Sàn diễn thời trang cao cấp",
    style_retro_futurism: "Hoài cổ tương lai",
    style_luxury_penthouse: "Penthouse sang trọng",
    style_traditional_garden: "Vườn thiền an tĩnh",
    style_pool_party: "Tiệc bể bơi",
    style_bar_pub: "Quán bar/Pub",
    style_bathroom_modern: "Phòng tắm hiện đại",
    style_gym_locker: "Phòng thay đồ Gym",
    style_café_window: "Cửa sổ quán cà phê",
    style_urban_rooftop: "Sân thượng thành thị",
    style_living_sofa: "Sofa phòng khách",
    style_desk_minimal: "Bàn làm việc tối giản",
    style_outdoor_park: "Công viên ngoài trời",
    style_shower_tile: "Gạch phòng tắm",
    style_street_neon: "Đường phố Neon",
    style_tet_holiday: "Ngày Tết",
    style_beach_sunset: "Hoàng hôn trên biển",
    style_sidewalk_eatery: "Quán ăn vỉa hè",
    style_yoga_retreat: "Khu nghỉ dưỡng Yoga",
    style_cocktail_bar: "Quầy bar Cocktail",
    style_airport_terminal: "Sảnh sân bay",
    style_classic_library: "Thư viện cổ điển",
    style_mountain_camping: "Cắm trại trên núi",
    style_art_gallery: "Triển lãm nghệ thuật",
    style_golf_course: "Sân golf",
    style_tet_flower_market: "Chợ hoa Tết",
    style_review: "Phong cách review",
    style_custom_prompt: "Prompt tùy chỉnh",

    // Camera Shots
    shot_auto: "Tự động",
    shot_els: "Toàn cảnh (ELS)",
    shot_ls: "Toàn thân (LS)",
    shot_mls: "Trung toàn (MLS)",
    shot_ms: "Trung cảnh (MS)",
    shot_mcu: "Cận trung (MCU)",
    shot_ecu: "Đặc tả (ECU)",

    // Aspect Ratios
    aspect_ratio_16_9: "16:9 (Ngang)",
    aspect_ratio_9_16: "9:16 (Dọc/Story)",
    aspect_ratio_1_1: "1:1 (Vuông)",

    // Genders
    gender_male: "Nam",
    gender_female: "Nữ",
    gender_any: "Bất kỳ",

    // Viral Ad Formulas
    viral_formula_idol_centric_name: "Câu chuyện Idol",
    viral_formula_idol_centric_desc: "Tập trung vào một ngày trong đời hoặc một câu chuyện cụ thể của idol, với sản phẩm được lồng ghép tự nhiên.",
    viral_formula_lyrical_narrative_name: "Tường thuật theo lời bài hát",
    viral_formula_lyrical_narrative_desc: "Câu chuyện được dẫn dắt bởi lời bài hát, tạo cảm giác như một MV ca nhạc mà sản phẩm là yếu tố chính.",
    viral_formula_vibe_montage_name: "Montage tạo cảm xúc",
    viral_formula_vibe_montage_desc: "Một chuỗi các cảnh quay thẩm mỹ, cắt nhanh để tạo ra một tâm trạng hoặc phong cách sống gắn liền với sản phẩm.",
    viral_formula_emotional_journey_name: "Hành trình cảm xúc",
    viral_formula_emotional_journey_desc: "Kể một câu chuyện có cung bậc cảm xúc rõ ràng (ví dụ: từ khó khăn đến thành công) mà sản phẩm đóng vai trò giải quyết vấn đề.",
    // Brand Film
    viral_formula_brand_origin_story_name: "Câu chuyện Nguồn gốc Thương hiệu",
    viral_formula_brand_origin_story_desc: "Kể câu chuyện về lý do thương hiệu ra đời, sứ mệnh và giá trị cốt lõi.",
    viral_formula_customer_testimonial_name: "Cảm nhận Khách hàng",
    viral_formula_customer_testimonial_desc: "Hiển thị hành trình của một khách hàng thực tế và sản phẩm đã tác động tích cực đến họ như thế nào.",
    viral_formula_behind_the_scenes_name: "Hậu trường Sản xuất",
    viral_formula_behind_the_scenes_desc: "Cho thấy tay nghề, con người hoặc quy trình đằng sau sản phẩm để xây dựng tính xác thực.",
    viral_formula_product_philosophy_name: "Triết lý Sản phẩm",
    viral_formula_product_philosophy_desc: "Giải thích 'lý do' đằng sau thiết kế, thành phần hoặc tính năng của sản phẩm, kết nối với một ý tưởng lớn hơn.",
    // Social Media Story
    viral_formula_ugc_challenge_name: "Thử thách UGC",
    viral_formula_ugc_challenge_desc: "Tạo ra một xu hướng hoặc thử thách đơn giản, dễ lặp lại để khuyến khích người dùng tạo nội dung.",
    viral_formula_quick_tip_tutorial_name: "Mẹo nhanh / Hướng dẫn",
    viral_formula_quick_tip_tutorial_desc: "Cung cấp giá trị bằng cách dạy khán giả điều gì đó hữu ích liên quan đến sản phẩm một cách nhanh gọn.",
    viral_formula_trending_sound_meme_name: "Âm thanh / Meme thịnh hành",
    viral_formula_trending_sound_meme_desc: "Phóng tác một định dạng âm thanh hoặc meme phổ biến cho phù hợp với lĩnh vực của thương hiệu một cách sáng tạo.",
    viral_formula_day_in_the_life_takeover_name: "Một ngày của Idol",
    viral_formula_day_in_the_life_takeover_desc: "Cho thấy một 'ngày trong đời' gần gũi từ góc nhìn của một thần tượng hoặc khách hàng sử dụng sản phẩm.",
    // Sales Video
    viral_formula_problem_agitate_solve_name: "Vấn đề - Kích động - Giải pháp",
    viral_formula_problem_agitate_solve_desc: "Xác định một vấn đề của khách hàng, nhấn mạnh vấn đề đó và giới thiệu sản phẩm như là giải pháp hoàn hảo.",
    viral_formula_unboxing_first_impression_name: "Đập hộp / Cảm nhận đầu tiên",
    viral_formula_unboxing_first_impression_desc: "Ghi lại sự phấn khích khi mở hộp và sử dụng sản phẩm lần đầu tiên.",
    viral_formula_before_after_transformation_name: "Trước & Sau khi biến đổi",
    viral_formula_before_after_transformation_desc: "Minh họa trực quan kết quả rõ ràng, hữu hình của việc sử dụng sản phẩm.",
    viral_formula_feature_benefit_demo_name: "Demo Tính năng - Lợi ích",
    viral_formula_feature_benefit_demo_desc: "Trình diễn rõ ràng một tính năng chính và giải thích lợi ích trực tiếp của nó cho khách hàng.",

    // Ad Goals
    ad_goal_conversion_name: "Chuyển đổi",
    ad_goal_conversion_desc: "Tập trung thúc đẩy doanh số ngay lập tức với lời kêu gọi hành động rõ ràng và nội dung tập trung vào lợi ích.",
    ad_goal_engagement_name: "Tương tác",
    ad_goal_engagement_desc: "Hướng đến việc nhận được lượt thích, bình luận và chia sẻ bằng cách giải trí, đặt câu hỏi hoặc tạo sự đồng cảm.",
    ad_goal_awareness_name: "Nhận diện",
    ad_goal_awareness_desc: "Giới thiệu thương hiệu hoặc sản phẩm đến đối tượng mới, tập trung vào câu chuyện thương hiệu và điểm bán hàng độc nhất.",

    // Blog Lengths
    blog_length_short: "Ngắn (~300 từ)",
    blog_length_medium: "Trung bình (~800 từ)",
    blog_length_long: "Dài (1500+ từ)",

    // Blog Goals
    blog_goal_seo: "Xếp hạng SEO",
    blog_goal_engagement: "Tương tác cộng đồng",
    blog_goal_leadgen: "Tạo khách hàng tiềm năng",
    blog_goal_product: "Quảng bá sản phẩm",

    // Humanize Tones
    humanize_everyday_user: "Người dùng hàng ngày",
    humanize_teacher: "Người hướng dẫn tận tình",
    humanize_online_reviewer: "Người review online",
    humanize_blog_commenter: "Người bình luận blog",
    
    // Video Usage Goals
    video_goal_mv_name: "Video ca nhạc (MV)",
    video_goal_mv_desc: "Một video ca nhạc hoàn chỉnh để quảng bá bài hát, có sự tham gia của idol và sản phẩm.",
    video_goal_brand_film_name: "Phim thương hiệu",
    video_goal_brand_film_desc: "Một bộ phim ngắn, đậm chất điện ảnh kể câu chuyện về giá trị của thương hiệu, với sản phẩm đóng một vai trò.",
    video_goal_social_story_name: "Story trên mạng xã hội",
    video_goal_social_story_desc: "Một video ngắn, định dạng dọc được thiết kế cho các nền tảng như Instagram Stories hoặc TikTok.",
    video_goal_sales_video_name: "Video bán hàng",
    video_goal_sales_video_desc: "Video phản hồi trực tiếp tập trung vào việc trình diễn sản phẩm và thúc đẩy chuyển đổi.",
  },
} as const;

export type Language = keyof typeof translations;
export type TranslationKey = keyof typeof translations['vi'];
