

import { GoogleGenAI, Modality, Type } from "@google/genai";
// FIX: Added missing types for storyboard and video features.
import { UploadedFile, Product, CharacterAnalysis, PointOfView, AIDetectionResult, HumanizeTone, Storyboard, StoryboardFrame, StoryboardContent, VideoDuration, AspectRatio } from '../types';
import { AD_COPY_PROMPT_TEMPLATE, BLOG_POST_PROMPT_TEMPLATE, BLOG_IDEAS_PROMPT_TEMPLATE, CONTEXT_SUGGESTION_PROMPT_TEMPLATE, AI_DETECTION_PROMPT_TEMPLATE, HUMANIZE_CONTENT_PROMPT_TEMPLATE, HUMANIZE_TONE_OPTIONS, HUMANIZE_AD_COPY_PROMPT_TEMPLATE, STORYBOARD_PROMPT_TEMPLATE, REGENERATE_FRAMES_PROMPT_TEMPLATE, HUMANIZE_SUGGESTIONS_PROMPT_TEMPLATE, YOUTUBE_ANALYSIS_PROMPT_TEMPLATE, STORYBOARD_FROM_INSPIRATION_PROMPT_TEMPLATE } from "../constants";
import { translations, Language } from "../localization";

// Per coding guidelines, initialize with API_KEY from environment.
// Storing it in a constant to ensure it's consistently applied across all API calls.
const API_KEY = process.env.API_KEY!;
const ai = new GoogleGenAI({ apiKey: API_KEY });

const imageModel = 'gemini-2.5-flash-image';
const textModel = 'gemini-3-flash-preview';
// FIX: Add model for video generation as per guidelines
const videoModel = 'veo-3.1-fast-generate-preview';


export interface AdCopy {
    headline: string;
    body: string;
    cta: string;
}

export interface HumanizeSuggestion {
    title: string;
    content: string;
}

export interface BlogPost {
  title: string;
  sections: { heading: string, paragraph:string }[];
}

export interface BlogIdea {
    topic: string;
    keywords: string;
}

const POV_MAP: Record<PointOfView, string> = {
    'FIRST_PERSON_I': "Ngôi thứ nhất (xưng 'tôi')",
    'SECOND_PERSON_YOU': "Ngôi thứ hai (gọi khán giả là 'bạn')",
    'THIRD_PERSON_HE_SHE': "Ngôi thứ ba (kể về 'anh ấy/cô ấy/họ')",
    'BRAND_WE': "Thương hiệu (xưng 'chúng tôi')"
};

export const generateEcomImage = async (prompt: string, images: (UploadedFile | null)[], retries = 3, delay = 2000): Promise<string> => {
    const imageParts = images
        .filter((image): image is UploadedFile => image !== null && !!image.base64)
        .map(image => ({
            inlineData: { data: image.base64!, mimeType: image.type }
        }));

    const parts: any[] = [...imageParts, { text: prompt }];

    for (let i = 0; i <= retries; i++) {
        try {
            const response = await ai.models.generateContent({
                model: imageModel,
                contents: { parts },
            });

            for (const part of response.candidates?.[0]?.content?.parts ?? []) {
                if (part.inlineData) {
                    return `data:${part.inlineData.mimeType};base64,${part.inlineData.data}`;
                }
            }
            throw new Error("No image was generated by the API.");
        } catch (error: any) {
            const errorMessage = error?.message || String(error);
            const isQuotaError = errorMessage.toLowerCase().includes("quota") || 
                                errorMessage.toLowerCase().includes("rate limit") ||
                                errorMessage.toLowerCase().includes("429");
            
            if (isQuotaError && i < retries) {
                const waitTime = delay * Math.pow(2, i);
                console.warn(`Quota exceeded. Retrying in ${waitTime}ms... (Attempt ${i + 1}/${retries})`);
                await new Promise(resolve => setTimeout(resolve, waitTime));
                continue;
            }
            throw error;
        }
    }
    throw new Error("Failed to generate image after multiple retries.");
};

export const extractImagePart = async (base64ImageData: string, mimeType: string, partToExtract: 'face' | 'product' | 'outfit'): Promise<string> => {
    let promptText = '';
    switch (partToExtract) {
        case 'face':
            promptText = "From the provided image, create and return a new image that is a tight, clean, high-quality crop focusing only on the person's face. Preserve the original quality and lighting.";
            break;
        case 'product':
            promptText = "From the provided image, create and return a new image that is a clean, high-quality crop of ONLY the main product. The product should be centered and isolated from the background as much as possible. If you cannot confidently identify a single main product, return the original image without any changes.";
            break;
        case 'outfit':
            promptText = "From the provided image, create and return a new image that is a high-quality crop showing the person's outfit from the torso down, or the most representative part of their clothing. Do not include the face.";
            break;
    }

    const parts = [
        { inlineData: { data: base64ImageData, mimeType: mimeType } },
        { text: promptText }
    ];

    const response = await ai.models.generateContent({
        model: imageModel,
        contents: { parts },
        config: { responseModalities: [Modality.IMAGE] },
    });

    for (const part of response.candidates?.[0]?.content?.parts ?? []) {
        if (part.inlineData) {
            return `data:${part.inlineData.mimeType};base64,${part.inlineData.data}`;
        }
    }
    throw new Error(`Failed to extract ${partToExtract} from the image.`);
};

export const addTextToImage = async (base64ImageData: string, mimeType: string, text: string, style: string, language: string, font: string): Promise<string> => {
    const prompt = `Add the following ${language} text to the image: "${text}".
    Style requirement: ${style}.
    Font requirement: Use a font that looks like '${font}'.
    The text should be seamlessly integrated, aesthetically pleasing, and highly legible, matching the professional quality of the image. Do not alter the original image otherwise.`;
    
    const parts = [
        { inlineData: { data: base64ImageData, mimeType: mimeType } },
        { text: prompt }
    ];

    const response = await ai.models.generateContent({
        model: imageModel, // 'gemini-2.5-flash-image-preview'
        contents: { parts },
        config: { responseModalities: [Modality.IMAGE, Modality.TEXT] },
    });
    
    for (const part of response.candidates?.[0]?.content?.parts ?? []) {
        if (part.inlineData) {
            return `data:${part.inlineData.mimeType};base64,${part.inlineData.data}`;
        }
    }
    throw new Error("Failed to add text to the image.");
};

export const generateAdCopy = async (
    product: Product,
    adGoal: string,
    adFormula: string,
    audience: string,
    insights: string
): Promise<AdCopy[]> => {
    let prompt = AD_COPY_PROMPT_TEMPLATE;

    const variables: Record<string, string | undefined> = {
        product_name: product.product_name,
        benefits: product.benefits.join(', '),
        usp: product.usp,
        brand_tone: product.notes,
        ad_goal: adGoal,
        ad_formula: adFormula,
        audience: audience,
        insights: insights || 'Nhu cầu chung của khách hàng về sản phẩm.',
    };

    for (const key in variables) {
        prompt = prompt.replace(new RegExp(`\\{${key}\\}`, 'g'), variables[key] || '');
    }

    const response = await ai.models.generateContent({
        model: textModel,
        contents: prompt,
        config: { 
            responseMimeType: "application/json",
            responseSchema: {
                type: Type.ARRAY,
                items: {
                    type: Type.OBJECT,
                    properties: {
                        headline: { type: Type.STRING },
                        body: { type: Type.STRING },
                        cta: { type: Type.STRING },
                    },
                    required: ["headline", "body", "cta"],
                    propertyOrdering: ["headline", "body", "cta"],
                }
            }
        }
    });

    try {
        let jsonStr = response.text.trim();
        const match = jsonStr.match(/^```(?:json)?\s*([\sS]*?)\s*```$/);
        if (match) {
            jsonStr = match[1];
        }
        const parsedJson = JSON.parse(jsonStr);
        if (Array.isArray(parsedJson) && parsedJson.every(item => item.headline && item.body && item.cta)) {
            return parsedJson as AdCopy[];
        } else {
            throw new Error("AI response is not a valid array of AdCopy objects.");
        }
    } catch (e) {
        console.error("Failed to parse JSON for ad copy from Gemini:", response.text, e);
        throw new Error("The AI returned an invalid format for ad copy. Please try again.");
    }
};

export const generateBlogPost = async (
    product: Product,
    topic: string,
    keywords: string,
    blogLength: string,
    blogGoal: string,
): Promise<BlogPost> => {
    let prompt = BLOG_POST_PROMPT_TEMPLATE;

    const variables: Record<string, string | undefined> = {
        topic,
        keywords,
        product_name: product.product_name,
        benefits: product.benefits.join(', '),
        brand_tone: product.notes,
        blog_length: blogLength,
        blog_goal: blogGoal,
    };

    for (const key in variables) {
        prompt = prompt.replace(new RegExp(`\\{${key}\\}`, 'g'), variables[key] || '');
    }

    const response = await ai.models.generateContent({
        model: textModel,
        contents: prompt,
        config: { 
            responseMimeType: "application/json",
            responseSchema: {
                type: Type.OBJECT,
                properties: {
                    title: { type: Type.STRING },
                    sections: { 
                        type: Type.ARRAY,
                        items: {
                            type: Type.OBJECT,
                            properties: {
                                heading: { type: Type.STRING },
                                paragraph: { type: Type.STRING },
                            },
                             required: ["heading", "paragraph"],
                        }
                    },
                },
                required: ["title", "sections"],
            }
        }
    });

    try {
        let jsonStr = response.text.trim();
        const match = jsonStr.match(/^```(?:json)?\s*([\sS]*?)\s*```$/);
        if (match) {
            jsonStr = match[1];
        }
        return JSON.parse(jsonStr);
    } catch (e) {
        console.error("Failed to parse JSON for blog post from Gemini:", response.text, e);
        throw new Error("The AI returned an invalid format for the blog post. Please try again.");
    }
};

export const generateBlogIdeas = async (
    product: Product,
    adFormula: string,
    audience: string,
    insights: string
): Promise<BlogIdea[]> => {
    let prompt = BLOG_IDEAS_PROMPT_TEMPLATE;

    const variables: Record<string, string | undefined> = {
        product_name: product.product_name,
        benefits: product.benefits.join(', '),
        brand_tone: product.notes,
        ad_formula: adFormula,
        audience: audience,
        insights: insights || 'Nhu cầu chung của khách hàng về sản phẩm.',
    };

    for (const key in variables) {
        prompt = prompt.replace(new RegExp(`\\{${key}\\}`, 'g'), variables[key] || '');
    }

    const response = await ai.models.generateContent({
        model: textModel,
        contents: prompt,
        config: { 
            responseMimeType: "application/json",
            responseSchema: {
                type: Type.ARRAY,
                items: {
                    type: Type.OBJECT,
                    properties: {
                        topic: { type: Type.STRING },
                        keywords: { type: Type.STRING },
                    },
                    required: ["topic", "keywords"],
                }
            }
        }
    });

    try {
        let jsonStr = response.text.trim();
        const match = jsonStr.match(/^```(?:json)?\s*([\sS]*?)\s*```$/);
        if (match) {
            jsonStr = match[1];
        }
        const parsedJson = JSON.parse(jsonStr);
        if (Array.isArray(parsedJson) && parsedJson.every(item => item.topic && item.keywords)) {
            return parsedJson as BlogIdea[];
        } else {
            throw new Error("AI response is not a valid array of BlogIdea objects.");
        }
    } catch (e) {
        console.error("Failed to parse JSON for blog ideas from Gemini:", response.text, e);
        throw new Error("The AI returned an invalid format for blog ideas. Please try again.");
    }
};

export const analyzeCharacterImage = async (base64ImageData: string, mimeType: string): Promise<CharacterAnalysis> => {
    const prompt = "Analyze the person in the image. Based on visual cues, infer their demographics and musical persona. Provide likely gender, age range, income level, lifestyle, location, and also their potential voice type (Male, Female, Duet), music vibe (Romantic, Powerful, Fun, Cinematic), and role (Singer, Rapper, Dancer, Storyteller). Respond ONLY with the JSON object.";

    const imagePart = {
        inlineData: { data: base64ImageData, mimeType: mimeType }
    };

    const response = await ai.models.generateContent({
        model: textModel, 
        contents: { parts: [imagePart, { text: prompt }] },
        config: {
            responseMimeType: "application/json",
            responseSchema: {
                type: Type.OBJECT,
                properties: {
                    gender: { 
                        type: Type.STRING,
                        enum: ['Male', 'Female', 'Other']
                    },
                    ageRange: { 
                        type: Type.STRING,
                        enum: ['18-24', '25-34', '35-44', '45+']
                    },
                    incomeLevel: {
                        type: Type.STRING,
                        description: "Estimated income level.",
                        enum: ['Low', 'Medium', 'High', 'Affluent']
                    },
                    lifestyle: {
                        type: Type.STRING,
                        description: "Inferred lifestyle.",
                        enum: ['Active & Outdoorsy', 'Minimalist & Modern', 'Luxury & Sophisticated', 'Family-Oriented', 'Tech-Savvy & Urban']
                    },
                    location: {
                        type: Type.STRING,
                        description: "Likely residential location type.",
                        enum: ['Urban City', 'Suburban', 'Rural Countryside']
                    },
                    voiceType: {
                        type: Type.STRING,
                        description: "Estimated voice type.",
                        enum: ['Male', 'Female', 'Duet']
                    },
                    musicVibe: {
                        type: Type.STRING,
                        description: "Inferred music vibe.",
                        enum: ['Romantic', 'Powerful', 'Fun', 'Cinematic']
                    },
                    role: {
                        type: Type.STRING,
                        description: "Likely role in a music context.",
                        enum: ['Singer', 'Rapper', 'Dancer', 'Storyteller']
                    }
                },
                required: ["gender", "ageRange", "incomeLevel", "lifestyle", "location", "voiceType", "musicVibe", "role"]
            }
        }
    });

    try {
        let jsonStr = response.text.trim();
        const match = jsonStr.match(/^```(?:json)?\s*([\sS]*?)\s*```$/);
        if (match) { jsonStr = match[1]; }
        return JSON.parse(jsonStr);
    } catch (e) {
        console.error("Failed to parse JSON for character analysis:", response.text, e);
        throw new Error("The AI returned an invalid format for character analysis.");
    }
};

export const generateCharacterInsights = async (
    product: Product,
    character1: CharacterAnalysis,
    character2?: CharacterAnalysis | null
): Promise<string[]> => {
    const character1Details = [
        `Giới tính: ${character1.gender}`,
        `Tuổi: ${character1.ageRange}`,
        character1.incomeLevel && `Thu nhập: ${character1.incomeLevel}`,
        character1.lifestyle && `Lối sống: ${character1.lifestyle}`,
        character1.location && `Địa điểm: ${character1.location}`
    ].filter(Boolean).join(', ');

    let character2Details = '';
    let isCouple = false;
    if (character2) {
        character2Details = [
            `Giới tính: ${character2.gender}`,
            `Tuổi: ${character2.ageRange}`,
            character2.incomeLevel && `Thu nhập: ${character2.incomeLevel}`,
            character2.lifestyle && `Lối sống: ${character2.lifestyle}`,
            character2.location && `Địa điểm: ${character2.location}`
        ].filter(Boolean).join(', ');
        
        // Check if they are different genders (excluding 'Other' and ensuring both have gender)
        if (character1.gender && character2.gender && character1.gender !== character2.gender && character1.gender !== 'Other' && character2.gender !== 'Other') {
            isCouple = true;
        }
    }

    const coupleInstruction = isCouple 
        ? `
        QUAN TRỌNG: Vì có hai đối tượng khác giới, hãy bổ sung các insight liên quan đến mối quan hệ cặp đôi (ví dụ: đang tán tỉnh, người yêu, vợ chồng). Các insight này nên phản ánh những mong muốn hoặc vấn đề chung trong mối quan hệ của họ liên quan đến sản phẩm.
        `
        : '';

    const prompt = `
        Bối cảnh:
        - Sản phẩm: ${product.product_name}
        - Lợi ích sản phẩm: ${product.benefits.join(', ')}
        - Đối tượng 1: ${character1Details}
        ${character2 ? `- Đối tượng 2: ${character2Details}` : ''}

        Dựa trên thông tin chi tiết về (các) đối tượng, hãy tạo ra một danh sách MẢNG JSON chứa từ 4 đến 6 "nỗi đau" hoặc "insight" sâu sắc. Các insight này cần phải phong phú và đa dạng hơn, phản ánh sự kết hợp giữa lối sống, thu nhập và địa điểm của họ.${coupleInstruction}
        Các insight cần ngắn gọn (dưới 15 từ), viết bằng tiếng Việt.
    `;

    const response = await ai.models.generateContent({
        model: textModel,
        contents: prompt,
        config: {
            responseMimeType: "application/json",
            responseSchema: {
                type: Type.ARRAY,
                items: { type: Type.STRING }
            }
        }
    });

    try {
        let jsonStr = response.text.trim();
        const match = jsonStr.match(/^```(?:json)?\s*([\sS]*?)\s*```$/);
        if (match) { jsonStr = match[1]; }
        const parsedJson = JSON.parse(jsonStr);
        if (Array.isArray(parsedJson)) {
            return parsedJson as string[];
        }
        throw new Error("AI response is not a valid array of strings.");
    } catch (e) {
        console.error("Failed to parse JSON for character insights:", response.text, e);
        throw new Error("The AI returned an invalid format for character insights.");
    }
};

export const generateContextSuggestions = async (
    product: Product,
    character: CharacterAnalysis,
    insights: string,
): Promise<string[]> => {
    let prompt = CONTEXT_SUGGESTION_PROMPT_TEMPLATE;
    const variables: Record<string, string | undefined> = {
        product_name: product.product_name,
        benefits: product.benefits.join(', '),
        gender: character.gender,
        age_range: character.ageRange,
        lifestyle: character.lifestyle,
        income: character.incomeLevel,
        location: character.location,
        insights: insights || 'Nhu cầu chung của khách hàng về sản phẩm.',
    };

    for (const key in variables) {
        prompt = prompt.replace(new RegExp(`\\{${key}\\}`, 'g'), variables[key] || '');
    }
    
    const response = await ai.models.generateContent({
        model: textModel,
        contents: prompt,
        config: {
            responseMimeType: "application/json",
            responseSchema: {
                type: Type.ARRAY,
                items: { type: Type.STRING }
            }
        }
    });

    try {
        let jsonStr = response.text.trim();
        const match = jsonStr.match(/^```(?:json)?\s*([\sS]*?)\s*```$/);
        if (match) {
            jsonStr = match[1];
        }
        const parsedJson = JSON.parse(jsonStr);
        if (Array.isArray(parsedJson)) {
            return parsedJson as string[];
        }
        throw new Error("AI response is not a valid array of strings.");
    } catch (e) {
        console.error("Failed to parse JSON for context suggestions:", response.text, e);
        throw new Error("The AI returned an invalid format for context suggestions.");
    }
};

export const detectAIContent = async (text: string): Promise<AIDetectionResult> => {
    let prompt = AI_DETECTION_PROMPT_TEMPLATE;
    prompt = prompt.replace('<<<TEXT_TO_ANALYZE>>>', text);

    const response = await ai.models.generateContent({
        model: textModel,
        contents: prompt,
        config: {
            responseMimeType: "application/json",
            responseSchema: {
                type: Type.OBJECT,
                properties: {
                    percentage: { type: Type.INTEGER },
                    reasoning: { type: Type.STRING },
                },
                required: ["percentage", "reasoning"],
            }
        }
    });

    try {
        let jsonStr = response.text.trim();
        const match = jsonStr.match(/^```(?:json)?\s*([\sS]*?)\s*```$/);
        if (match) { jsonStr = match[1]; }
        return JSON.parse(jsonStr);
    } catch (e) {
        console.error("Failed to parse JSON for AI detection:", response.text, e);
        throw new Error("The AI returned an invalid format for AI detection.");
    }
};

export const humanizeContent = async (text: string, tone: HumanizeTone, pov: PointOfView, customPersona: string, contentType: 'ad' | 'blog' | 'storyboard' = 'blog'): Promise<string> => {
    let prompt: string;

    switch (contentType) {
        case 'ad':
            prompt = HUMANIZE_AD_COPY_PROMPT_TEMPLATE;
            break;
        case 'blog':
        case 'storyboard':
        default:
            prompt = HUMANIZE_CONTENT_PROMPT_TEMPLATE;
            break;
    }
    
    const toneOption = HUMANIZE_TONE_OPTIONS.find(t => t.id === tone);
    // FIX: Property 'vi' does not exist on type '{ en: ... }'. Corrected translations object type inference by fixing vi object.
    const toneName = toneOption ? translations.vi[toneOption.nameKey] : 'người dùng đời thường';
    const povDescription = POV_MAP[pov] || "ngôi thứ hai (bạn)";
    const customPersonaInstruction = customPersona.trim() 
        ? `Additionally, adopt this specific personality: "${customPersona.trim()}". This is more important than the general tone.`
        : '';

    prompt = prompt.replace('{tone}', toneName);
    prompt = prompt.replace('{point_of_view}', povDescription);
    prompt = prompt.replace('{custom_persona_instruction}', customPersonaInstruction);
    prompt = prompt.replace('<<<ORIGINAL_TEXT>>>', text);
    
    const response = await ai.models.generateContent({
        model: textModel,
        contents: prompt,
    });

    return response.text;
};

export const getHumanizeSuggestions = async (
    originalText: string,
    aiDetectionResult: AIDetectionResult,
    product: Product,
    character: CharacterAnalysis | null,
    insights: string,
    context: string
): Promise<HumanizeSuggestion[]> => {
    let prompt = HUMANIZE_SUGGESTIONS_PROMPT_TEMPLATE;

    const characterDesc = character 
        ? `Gender: ${character.gender}, Age: ${character.ageRange}, Lifestyle: ${character.lifestyle}`
        : 'General audience for the product.';

    const variables: Record<string, string | undefined> = {
        ai_score: String(aiDetectionResult.percentage),
        ai_reasoning: aiDetectionResult.reasoning,
        product_name: product.product_name,
        benefits: product.benefits.join(', '),
        character_desc: characterDesc,
        insights: insights,
        context: context,
    };

    prompt = prompt.replace('<<<ORIGINAL_TEXT>>>', originalText);
    for (const key in variables) {
        prompt = prompt.replace(new RegExp(`\\{${key}\\}`, 'g'), variables[key] || '');
    }

    const response = await ai.models.generateContent({
        model: textModel,
        contents: prompt,
        config: {
            responseMimeType: "application/json",
            responseSchema: {
                type: Type.ARRAY,
                items: {
                    type: Type.OBJECT,
                    properties: {
                        title: { type: Type.STRING },
                        content: { type: Type.STRING },
                    },
                    required: ["title", "content"],
                }
            }
        }
    });
    
    try {
        let jsonStr = response.text.trim();
        const match = jsonStr.match(/^```(?:json)?\s*([\sS]*?)\s*```$/);
        if (match) { jsonStr = match[1]; }
        return JSON.parse(jsonStr);
    } catch (e) {
        console.error("Failed to parse JSON for humanize suggestions:", response.text, e);
        throw new Error("The AI returned an invalid format for humanize suggestions.");
    }
};

// FIX: Update function signature to accept musicVibe and lyrics.
export const generateStoryboard = async (
    product: Product,
    videoDuration: VideoDuration,
    aspectRatio: AspectRatio,
    idolFile: UploadedFile | null,
    supportingIdolFile: UploadedFile | null,
    productFile: UploadedFile | null,
    outfitFile: UploadedFile | null,
    context: string,
    audience: string,
    customerInsights: string,
    usageGoal: string,
    adFormula: string,
    language: Language,
    musicVibe: string,
    lyrics: string
): Promise<Storyboard> => {
    const frameCount = parseInt(videoDuration.replace('s', '')) / 3;
    let prompt = STORYBOARD_PROMPT_TEMPLATE;

    const langName = language === 'vi' ? 'VIETNAMESE' : 'ENGLISH';

    // FIX: Add musicVibe and lyrics to the variables object.
    const variables: Record<string, string | undefined> = {
        language: langName,
        frame_count: String(frameCount),
        product_name: product.product_name,
        benefits: product.benefits.join(', '),
        brand_tone: product.notes,
        video_duration: videoDuration,
        aspect_ratio: aspectRatio,
        audience: audience,
        insights: customerInsights,
        usage_goal: usageGoal,
        ad_formula: adFormula,
        context: context,
        character_desc: idolFile ? "A character whose appearance is based on a reference image." : "A character suitable for the target audience.",
        supporting_character_desc: supportingIdolFile ? "A supporting character based on a reference image." : "Not applicable.",
        music_vibe: musicVibe,
        lyrics: lyrics || "No lyrics provided.",
    };

    for (const key in variables) {
        prompt = prompt.replace(new RegExp(`\\{${key}\\}`, 'g'), variables[key] || '');
    }
    
    const response = await ai.models.generateContent({
        model: textModel,
        contents: prompt,
        config: { 
            responseMimeType: "application/json",
            responseSchema: {
                type: Type.OBJECT,
                properties: {
                    script_full: { type: Type.STRING },
                    storyboard: {
                        type: Type.ARRAY,
                        items: {
                            type: Type.OBJECT,
                            properties: {
                                scene: { type: Type.STRING },
                                action: { type: Type.STRING },
                                dialogue: { type: Type.STRING },
                                transition: { type: Type.STRING },
                                image_prompt: { type: Type.STRING },
                            },
                            required: ["scene", "action", "dialogue", "transition", "image_prompt"],
                        }
                    },
                },
                required: ["script_full", "storyboard"],
            }
        }
    });

    try {
        let jsonStr = response.text.trim();
        const match = jsonStr.match(/^```(?:json)?\s*([\sS]*?)\s*```$/);
        if (match) {
            jsonStr = match[1];
        }
        const parsedJson = JSON.parse(jsonStr);
        if (parsedJson.script_full && Array.isArray(parsedJson.storyboard)) {
            return parsedJson as Storyboard;
        } else {
             throw new Error("AI response is not a valid Storyboard object.");
        }
    } catch (e) {
        console.error("Failed to parse JSON for storyboard from Gemini:", response.text, e);
        throw new Error("The AI returned an invalid format for the storyboard. Please try again.");
    }
};

export const regenerateStoryboardFrames = async (script: string, context: any): Promise<StoryboardFrame[]> => {
    let prompt = REGENERATE_FRAMES_PROMPT_TEMPLATE;
    const langName = context.language === 'vi' ? 'VIETNAMESE' : 'ENGLISH';
    const frameCount = parseInt(context.videoDuration.replace('s', '')) / 3;

    const variables: Record<string, string | undefined> = {
        language: langName,
        script: script,
        frame_count: String(frameCount),
        product_name: context.product.product_name,
        brand_tone: context.product.notes,
        aspect_ratio: context.aspectRatio,
        audience: context.audience,
        context: context.context,
        character_desc: context.idolFile ? "A character whose appearance is based on a reference image." : "A character suitable for the target audience.",
        supporting_character_desc: context.supportingIdolFile ? "A supporting character based on a reference image." : "Not applicable.",
    };

    for (const key in variables) {
        prompt = prompt.replace(new RegExp(`\\{${key}\\}`, 'g'), variables[key] || '');
    }

    const response = await ai.models.generateContent({
        model: textModel,
        contents: prompt,
        config: { 
            responseMimeType: "application/json",
            responseSchema: {
                type: Type.ARRAY,
                items: {
                    type: Type.OBJECT,
                    properties: {
                        scene: { type: Type.STRING },
                        action: { type: Type.STRING },
                        dialogue: { type: Type.STRING },
                        transition: { type: Type.STRING },
                        image_prompt: { type: Type.STRING },
                    },
                    required: ["scene", "action", "dialogue", "transition", "image_prompt"],
                }
            }
        }
    });

    try {
        let jsonStr = response.text.trim();
        const match = jsonStr.match(/^```(?:json)?\s*([\sS]*?)\s*```$/);
        if (match) {
            jsonStr = match[1];
        }
        const parsedJson = JSON.parse(jsonStr);
        if (Array.isArray(parsedJson)) {
            return parsedJson as StoryboardFrame[];
        } else {
             throw new Error("AI response is not a valid array of StoryboardFrame objects.");
        }
    } catch (e) {
        console.error("Failed to parse JSON for regenerated storyboard frames from Gemini:", response.text, e);
        throw new Error("The AI returned an invalid format for the regenerated storyboard frames. Please try again.");
    }
};

export const generateStoryboardFromInspiration = async (
    inspiration: { youtubeUrl?: string; file?: UploadedFile },
    context: {
        product: Product,
        videoDuration: VideoDuration,
        aspectRatio: AspectRatio,
        idolFile: UploadedFile | null,
        supportingIdolFile: UploadedFile | null,
        language: Language,
    }
): Promise<Storyboard> => {
    let inspirationAnalysis = '';

    if (inspiration.youtubeUrl) {
        let analysisPrompt = YOUTUBE_ANALYSIS_PROMPT_TEMPLATE.replace('{youtube_url}', inspiration.youtubeUrl);
        
        const analysisResponse = await ai.models.generateContent({
            model: textModel,
            contents: analysisPrompt,
            config: {
                tools: [{googleSearch: {}}],
            },
        });
        
        inspirationAnalysis = analysisResponse.text;
        
        if (!inspirationAnalysis || inspirationAnalysis.length < 100) { // Arbitrary length check for a meaningful analysis
            throw new Error("Could not analyze the YouTube link. It might be private, unavailable, or lack sufficient public information.");
        }

    } else if (inspiration.file) {
        if (inspiration.file.type === 'text/plain' && inspiration.file.file) {
            inspirationAnalysis = await inspiration.file.file.text();
        } else {
            throw new Error("File type not supported for analysis. Please use a .txt file.");
        }
    } else {
        throw new Error("No inspiration source provided.");
    }

    const frameCount = parseInt(context.videoDuration.replace('s', '')) / 3;
    let storyboardPrompt = STORYBOARD_FROM_INSPIRATION_PROMPT_TEMPLATE;

    const langName = context.language === 'vi' ? 'VIETNAMESE' : 'ENGLISH';
    
    const variables: Record<string, string | undefined> = {
        language: langName,
        frame_count: String(frameCount),
        inspiration_analysis: inspirationAnalysis,
        product_name: context.product.product_name,
        benefits: context.product.benefits.join(', '),
        brand_tone: context.product.notes,
        video_duration: context.videoDuration,
        aspect_ratio: context.aspectRatio,
        character_desc: context.idolFile ? "A character whose appearance is based on a reference image." : "A character suitable for the target audience.",
        supporting_character_desc: context.supportingIdolFile ? "A supporting character based on a reference image." : "Not applicable.",
    };

    for (const key in variables) {
        storyboardPrompt = storyboardPrompt.replace(new RegExp(`\\{${key}\\}`, 'g'), variables[key] || '');
    }

    const response = await ai.models.generateContent({
        model: textModel,
        contents: storyboardPrompt,
        config: { 
            responseMimeType: "application/json",
            responseSchema: {
                type: Type.OBJECT,
                properties: {
                    script_full: { type: Type.STRING },
                    storyboard: {
                        type: Type.ARRAY,
                        items: {
                            type: Type.OBJECT,
                            properties: {
                                scene: { type: Type.STRING },
                                action: { type: Type.STRING },
                                dialogue: { type: Type.STRING },
                                transition: { type: Type.STRING },
                                image_prompt: { type: Type.STRING },
                            },
                            required: ["scene", "action", "dialogue", "transition", "image_prompt"],
                        }
                    },
                },
                required: ["script_full", "storyboard"],
            }
        }
    });

    try {
        let jsonStr = response.text.trim();
        const match = jsonStr.match(/^```(?:json)?\s*([\sS]*?)\s*```$/);
        if (match) {
            jsonStr = match[1];
        }
        const parsedJson = JSON.parse(jsonStr);
        if (parsedJson.script_full && Array.isArray(parsedJson.storyboard)) {
            return parsedJson as Storyboard;
        } else {
             throw new Error("AI response is not a valid Storyboard object.");
        }
    } catch (e) {
        console.error("Failed to parse JSON for storyboard from Gemini:", response.text, e);
        throw new Error("The AI returned an invalid format for the storyboard. Please try again.");
    }
};

export const generateVideo = async (prompt: string, image: UploadedFile, aspectRatio: AspectRatio, onProgress: (progress: string) => void): Promise<Blob> => {
    onProgress("Initializing video generation...");
    console.log(`Generating video for prompt: ${prompt}`);
    let operation = await ai.models.generateVideos({
        model: videoModel,
        prompt: prompt,
        image: {
            imageBytes: image.base64!,
            mimeType: image.type,
        },
        config: { numberOfVideos: 1 }
    });
    
    while (!operation.done) {
        onProgress("AI is creating... This may take a few minutes.");
        await new Promise(resolve => setTimeout(resolve, 10000));
        operation = await ai.operations.getVideosOperation({ operation: operation });
    }

    const downloadLink = operation.response?.generatedVideos?.[0]?.video?.uri;
    if (!downloadLink) {
        throw new Error("Video generation completed but no download link was found.");
    }
    onProgress("Finalizing video...");
    const response = await fetch(`${downloadLink}&key=${API_KEY}`);
    if (!response.ok) {
        throw new Error(`Failed to download video: ${response.statusText}`);
    }
    return response.blob();
};

export const generateVideoClipFromFrames = async (frame1: StoryboardFrame, frame2: StoryboardFrame, aspectRatio: AspectRatio, onProgress: (progress: string) => void): Promise<Blob> => {
    onProgress("Initializing clip generation...");
    // This is a simplified placeholder. A real implementation would be more complex.
    const prompt = `Create a smooth video transition from a scene described as "${frame1.image_prompt}" to a scene described as "${frame2.image_prompt}".`;
    let operation = await ai.models.generateVideos({ model: videoModel, prompt, config: { numberOfVideos: 1 } });
     while (!operation.done) {
        onProgress("AI is creating clip... This may take a minute.");
        await new Promise(resolve => setTimeout(resolve, 10000));
        operation = await ai.operations.getVideosOperation({ operation: operation });
    }
    const downloadLink = operation.response?.generatedVideos?.[0]?.video?.uri;
     if (!downloadLink) throw new Error("Video generation failed.");
    onProgress("Finalizing clip...");
    const response = await fetch(`${downloadLink}&key=${API_KEY}`);
    return response.blob();
};

export const generateVideoFromStoryboard = async (storyboardContent: StoryboardContent, onProgress: (progress: string) => void): Promise<Blob> => {
    onProgress("Initializing full video generation from storyboard...");
    let operation = await ai.models.generateVideos({ model: videoModel, prompt: storyboardContent.storyboard.script_full, config: { numberOfVideos: 1 } });
     while (!operation.done) {
        onProgress("AI is creating full video... This may take several minutes.");
        await new Promise(resolve => setTimeout(resolve, 10000));
        operation = await ai.operations.getVideosOperation({ operation: operation });
    }
    const downloadLink = operation.response?.generatedVideos?.[0]?.video?.uri;
    if (!downloadLink) throw new Error("Video generation failed.");
    onProgress("Finalizing video...");
    const response = await fetch(`${downloadLink}&key=${API_KEY}`);
    return response.blob();
};